# Usamos la imagen base de Node.js
FROM node:14

# Establecemos el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copiamos los archivos package.json y package-lock.json (si los tienes)
COPY package*.json ./

# Instalamos las dependencias de Node.js
RUN npm install

# Copiamos todo el código fuente al contenedor
COPY . .

# Exponemos el puerto que la aplicación va a utilizar (puedes cambiar este puerto si es necesario)
EXPOSE 3000

# Establecemos las variables de entorno desde los build args (los pasamos desde GitHub Actions)
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT

ENV DB_NAME=$DB_NAME \
    DB_USER=$DB_USER \
    DB_PASSWORD=$DB_PASSWORD \
    DB_HOST=$DB_HOST \
    DB_PORT=$DB_PORT

ENV SERVER_PORT=3000
EXPOSE 3000

# Comando para ejecutar la aplicación Node.js
CMD ["node", "server.js"]
