name: Docker Image CI/CD for Login User Microservice

on:
  push:
    paths:
      - 'Backend_tshirtop1/Authentication_and_Authorization/login_user/**'
    branches:
      - 'test'
  pull_request:
    paths:
      - 'Backend_tshirtop1/Authentication_and_Authorization/register_user/**'
    branches: ["QA", "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Login en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        #username: ${{ secrets.DOCKER_USERNAME }}
        #password: ${{ secrets.DOCKER_PASSWORD }}

    